// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: type.proto

package type_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemArray     []*Item                `protobuf:"bytes,1,rep,name=item_array,json=itemArray,proto3" json:"item_array,omitempty"`      // []Item   对象数组
	StrArray      []string               `protobuf:"bytes,2,rep,name=str_array,json=strArray,proto3" json:"str_array,omitempty"`         // []string  字符串数组
	IntArray      []int32                `protobuf:"varint,3,rep,packed,name=int_array,json=intArray,proto3" json:"int_array,omitempty"` // []int32   整型数组
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRequest) Reset() {
	*x = TypeRequest{}
	mi := &file_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRequest) ProtoMessage() {}

func (x *TypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRequest.ProtoReflect.Descriptor instead.
func (*TypeRequest) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{1}
}

func (x *TypeRequest) GetItemArray() []*Item {
	if x != nil {
		return x.ItemArray
	}
	return nil
}

func (x *TypeRequest) GetStrArray() []string {
	if x != nil {
		return x.StrArray
	}
	return nil
}

func (x *TypeRequest) GetIntArray() []int32 {
	if x != nil {
		return x.IntArray
	}
	return nil
}

type TypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemMap       map[string]*Item       `protobuf:"bytes,1,rep,name=item_map,json=itemMap,proto3" json:"item_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map[string]Item  对象map
	StrMap        map[string]string      `protobuf:"bytes,2,rep,name=str_map,json=strMap,proto3" json:"str_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`    // map[string]string 字符串map
	IntMap        map[string]int32       `protobuf:"bytes,3,rep,name=int_map,json=intMap,proto3" json:"int_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`   // map[string]int32 整型map
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeResponse) Reset() {
	*x = TypeResponse{}
	mi := &file_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeResponse) ProtoMessage() {}

func (x *TypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeResponse.ProtoReflect.Descriptor instead.
func (*TypeResponse) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{2}
}

func (x *TypeResponse) GetItemMap() map[string]*Item {
	if x != nil {
		return x.ItemMap
	}
	return nil
}

func (x *TypeResponse) GetStrMap() map[string]string {
	if x != nil {
		return x.StrMap
	}
	return nil
}

func (x *TypeResponse) GetIntMap() map[string]int32 {
	if x != nil {
		return x.IntMap
	}
	return nil
}

var File_type_proto protoreflect.FileDescriptor

const file_type_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"type.proto\x12\n" +
	"type_proto\"*\n" +
	"\x04Item\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"x\n" +
	"\vTypeRequest\x12/\n" +
	"\n" +
	"item_array\x18\x01 \x03(\v2\x10.type_proto.ItemR\titemArray\x12\x1b\n" +
	"\tstr_array\x18\x02 \x03(\tR\bstrArray\x12\x1b\n" +
	"\tint_array\x18\x03 \x03(\x05R\bintArray\"\x92\x03\n" +
	"\fTypeResponse\x12@\n" +
	"\bitem_map\x18\x01 \x03(\v2%.type_proto.TypeResponse.ItemMapEntryR\aitemMap\x12=\n" +
	"\astr_map\x18\x02 \x03(\v2$.type_proto.TypeResponse.StrMapEntryR\x06strMap\x12=\n" +
	"\aint_map\x18\x03 \x03(\v2$.type_proto.TypeResponse.IntMapEntryR\x06intMap\x1aL\n" +
	"\fItemMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.type_proto.ItemR\x05value:\x028\x01\x1a9\n" +
	"\vStrMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vIntMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012M\n" +
	"\vTypeService\x12>\n" +
	"\aGetType\x12\x17.type_proto.TypeRequest\x1a\x18.type_proto.TypeResponse\"\x00B\x0fZ\r./;type_protob\x06proto3"

var (
	file_type_proto_rawDescOnce sync.Once
	file_type_proto_rawDescData []byte
)

func file_type_proto_rawDescGZIP() []byte {
	file_type_proto_rawDescOnce.Do(func() {
		file_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_type_proto_rawDesc), len(file_type_proto_rawDesc)))
	})
	return file_type_proto_rawDescData
}

var file_type_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_type_proto_goTypes = []any{
	(*Item)(nil),         // 0: type_proto.Item
	(*TypeRequest)(nil),  // 1: type_proto.TypeRequest
	(*TypeResponse)(nil), // 2: type_proto.TypeResponse
	nil,                  // 3: type_proto.TypeResponse.ItemMapEntry
	nil,                  // 4: type_proto.TypeResponse.StrMapEntry
	nil,                  // 5: type_proto.TypeResponse.IntMapEntry
}
var file_type_proto_depIdxs = []int32{
	0, // 0: type_proto.TypeRequest.item_array:type_name -> type_proto.Item
	3, // 1: type_proto.TypeResponse.item_map:type_name -> type_proto.TypeResponse.ItemMapEntry
	4, // 2: type_proto.TypeResponse.str_map:type_name -> type_proto.TypeResponse.StrMapEntry
	5, // 3: type_proto.TypeResponse.int_map:type_name -> type_proto.TypeResponse.IntMapEntry
	0, // 4: type_proto.TypeResponse.ItemMapEntry.value:type_name -> type_proto.Item
	1, // 5: type_proto.TypeService.GetType:input_type -> type_proto.TypeRequest
	2, // 6: type_proto.TypeService.GetType:output_type -> type_proto.TypeResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_type_proto_init() }
func file_type_proto_init() {
	if File_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_type_proto_rawDesc), len(file_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_type_proto_goTypes,
		DependencyIndexes: file_type_proto_depIdxs,
		MessageInfos:      file_type_proto_msgTypes,
	}.Build()
	File_type_proto = out.File
	file_type_proto_goTypes = nil
	file_type_proto_depIdxs = nil
}
