// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: type.proto

package type_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TypeService_GetType_FullMethodName = "/type_proto.TypeService/GetType"
)

// TypeServiceClient is the client API for TypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TypeServiceClient interface {
	GetType(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (*TypeResponse, error)
}

type typeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTypeServiceClient(cc grpc.ClientConnInterface) TypeServiceClient {
	return &typeServiceClient{cc}
}

func (c *typeServiceClient) GetType(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (*TypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeResponse)
	err := c.cc.Invoke(ctx, TypeService_GetType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TypeServiceServer is the server API for TypeService service.
// All implementations must embed UnimplementedTypeServiceServer
// for forward compatibility.
type TypeServiceServer interface {
	GetType(context.Context, *TypeRequest) (*TypeResponse, error)
	mustEmbedUnimplementedTypeServiceServer()
}

// UnimplementedTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTypeServiceServer struct{}

func (UnimplementedTypeServiceServer) GetType(context.Context, *TypeRequest) (*TypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetType not implemented")
}
func (UnimplementedTypeServiceServer) mustEmbedUnimplementedTypeServiceServer() {}
func (UnimplementedTypeServiceServer) testEmbeddedByValue()                     {}

// UnsafeTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TypeServiceServer will
// result in compilation errors.
type UnsafeTypeServiceServer interface {
	mustEmbedUnimplementedTypeServiceServer()
}

func RegisterTypeServiceServer(s grpc.ServiceRegistrar, srv TypeServiceServer) {
	// If the following call panics, it indicates UnimplementedTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TypeService_ServiceDesc, srv)
}

func _TypeService_GetType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TypeServiceServer).GetType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TypeService_GetType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TypeServiceServer).GetType(ctx, req.(*TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TypeService_ServiceDesc is the grpc.ServiceDesc for TypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "type_proto.TypeService",
	HandlerType: (*TypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetType",
			Handler:    _TypeService_GetType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "type.proto",
}
