// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: user/user.proto

package user

import (
	basic "go_learning/04_micro/grpc/multiple_proto/proto/basic"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_user_proto protoreflect.FileDescriptor

const file_user_user_proto_rawDesc = "" +
	"\n" +
	"\x0fuser/user.proto\x12\x0emultiple_proto\x1a\x11basic/basic.proto2W\n" +
	"\vUserService\x12H\n" +
	"\aGetUser\x12\x1c.multiple_proto.BasicRequest\x1a\x1d.multiple_proto.BasicResponse\"\x00B:Z8go_learning/04_micro/grpc/multiple_proto/proto/user;userb\x06proto3"

var file_user_user_proto_goTypes = []any{
	(*basic.BasicRequest)(nil),  // 0: multiple_proto.BasicRequest
	(*basic.BasicResponse)(nil), // 1: multiple_proto.BasicResponse
}
var file_user_user_proto_depIdxs = []int32{
	0, // 0: multiple_proto.UserService.GetUser:input_type -> multiple_proto.BasicRequest
	1, // 1: multiple_proto.UserService.GetUser:output_type -> multiple_proto.BasicResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_proto_init() }
func file_user_user_proto_init() {
	if File_user_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_proto_rawDesc), len(file_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_user_proto_goTypes,
		DependencyIndexes: file_user_user_proto_depIdxs,
	}.Build()
	File_user_user_proto = out.File
	file_user_user_proto_goTypes = nil
	file_user_user_proto_depIdxs = nil
}
