// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: basic/basic.proto

package basic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicRequest) Reset() {
	*x = BasicRequest{}
	mi := &file_basic_basic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicRequest) ProtoMessage() {}

func (x *BasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_basic_basic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicRequest.ProtoReflect.Descriptor instead.
func (*BasicRequest) Descriptor() ([]byte, []int) {
	return file_basic_basic_proto_rawDescGZIP(), []int{0}
}

func (x *BasicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BasicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicResponse) Reset() {
	*x = BasicResponse{}
	mi := &file_basic_basic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicResponse) ProtoMessage() {}

func (x *BasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_basic_basic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicResponse.ProtoReflect.Descriptor instead.
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return file_basic_basic_proto_rawDescGZIP(), []int{1}
}

func (x *BasicResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BasicResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BasicResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_basic_basic_proto protoreflect.FileDescriptor

const file_basic_basic_proto_rawDesc = "" +
	"\n" +
	"\x11basic/basic.proto\x12\x0emultiple_proto\x1a\x19google/protobuf/any.proto\"\"\n" +
	"\fBasicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"g\n" +
	"\rBasicResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12(\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB<Z:go_learning/04_micro/grpc/multiple_proto/proto/basic;basicb\x06proto3"

var (
	file_basic_basic_proto_rawDescOnce sync.Once
	file_basic_basic_proto_rawDescData []byte
)

func file_basic_basic_proto_rawDescGZIP() []byte {
	file_basic_basic_proto_rawDescOnce.Do(func() {
		file_basic_basic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basic_basic_proto_rawDesc), len(file_basic_basic_proto_rawDesc)))
	})
	return file_basic_basic_proto_rawDescData
}

var file_basic_basic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_basic_basic_proto_goTypes = []any{
	(*BasicRequest)(nil),  // 0: multiple_proto.BasicRequest
	(*BasicResponse)(nil), // 1: multiple_proto.BasicResponse
	(*anypb.Any)(nil),     // 2: google.protobuf.Any
}
var file_basic_basic_proto_depIdxs = []int32{
	2, // 0: multiple_proto.BasicResponse.data:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_basic_basic_proto_init() }
func file_basic_basic_proto_init() {
	if File_basic_basic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basic_basic_proto_rawDesc), len(file_basic_basic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basic_basic_proto_goTypes,
		DependencyIndexes: file_basic_basic_proto_depIdxs,
		MessageInfos:      file_basic_basic_proto_msgTypes,
	}.Build()
	File_basic_basic_proto = out.File
	file_basic_basic_proto_goTypes = nil
	file_basic_basic_proto_depIdxs = nil
}
