// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: multiple_service.proto

package mutiple_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_multiple_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_multiple_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_multiple_service_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_multiple_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_multiple_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_multiple_service_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_multiple_service_proto protoreflect.FileDescriptor

const file_multiple_service_proto_rawDesc = "" +
	"\n" +
	"\x16multiple_service.proto\x12\x0fmutiple_service\"\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2Q\n" +
	"\fVideoService\x12A\n" +
	"\bGetVideo\x12\x18.mutiple_service.Request\x1a\x19.mutiple_service.Response\"\x002Q\n" +
	"\fOrderService\x12A\n" +
	"\bGetOrder\x12\x18.mutiple_service.Request\x1a\x19.mutiple_service.Response\"\x00B\x14Z\x12./;mutiple_serviceb\x06proto3"

var (
	file_multiple_service_proto_rawDescOnce sync.Once
	file_multiple_service_proto_rawDescData []byte
)

func file_multiple_service_proto_rawDescGZIP() []byte {
	file_multiple_service_proto_rawDescOnce.Do(func() {
		file_multiple_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multiple_service_proto_rawDesc), len(file_multiple_service_proto_rawDesc)))
	})
	return file_multiple_service_proto_rawDescData
}

var file_multiple_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_multiple_service_proto_goTypes = []any{
	(*Request)(nil),  // 0: mutiple_service.Request
	(*Response)(nil), // 1: mutiple_service.Response
}
var file_multiple_service_proto_depIdxs = []int32{
	0, // 0: mutiple_service.VideoService.GetVideo:input_type -> mutiple_service.Request
	0, // 1: mutiple_service.OrderService.GetOrder:input_type -> mutiple_service.Request
	1, // 2: mutiple_service.VideoService.GetVideo:output_type -> mutiple_service.Response
	1, // 3: mutiple_service.OrderService.GetOrder:output_type -> mutiple_service.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_multiple_service_proto_init() }
func file_multiple_service_proto_init() {
	if File_multiple_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multiple_service_proto_rawDesc), len(file_multiple_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_multiple_service_proto_goTypes,
		DependencyIndexes: file_multiple_service_proto_depIdxs,
		MessageInfos:      file_multiple_service_proto_msgTypes,
	}.Build()
	File_multiple_service_proto = out.File
	file_multiple_service_proto_goTypes = nil
	file_multiple_service_proto_depIdxs = nil
}
