// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: type.proto

package type_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 各种基本类型
type TypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A1            float64                `protobuf:"fixed64,1,opt,name=a1,proto3" json:"a1,omitempty"`
	A2            float32                `protobuf:"fixed32,2,opt,name=a2,proto3" json:"a2,omitempty"`
	A3            int32                  `protobuf:"varint,3,opt,name=a3,proto3" json:"a3,omitempty"`
	A4            int64                  `protobuf:"varint,4,opt,name=a4,proto3" json:"a4,omitempty"`
	A5            uint32                 `protobuf:"varint,5,opt,name=a5,proto3" json:"a5,omitempty"`
	A6            uint64                 `protobuf:"varint,6,opt,name=a6,proto3" json:"a6,omitempty"`
	A7            bool                   `protobuf:"varint,7,opt,name=a7,proto3" json:"a7,omitempty"`
	A8            string                 `protobuf:"bytes,8,opt,name=a8,proto3" json:"a8,omitempty"`
	A9            []byte                 `protobuf:"bytes,9,opt,name=a9,proto3" json:"a9,omitempty"` // []byte
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRequest) Reset() {
	*x = TypeRequest{}
	mi := &file_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRequest) ProtoMessage() {}

func (x *TypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRequest.ProtoReflect.Descriptor instead.
func (*TypeRequest) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{0}
}

func (x *TypeRequest) GetA1() float64 {
	if x != nil {
		return x.A1
	}
	return 0
}

func (x *TypeRequest) GetA2() float32 {
	if x != nil {
		return x.A2
	}
	return 0
}

func (x *TypeRequest) GetA3() int32 {
	if x != nil {
		return x.A3
	}
	return 0
}

func (x *TypeRequest) GetA4() int64 {
	if x != nil {
		return x.A4
	}
	return 0
}

func (x *TypeRequest) GetA5() uint32 {
	if x != nil {
		return x.A5
	}
	return 0
}

func (x *TypeRequest) GetA6() uint64 {
	if x != nil {
		return x.A6
	}
	return 0
}

func (x *TypeRequest) GetA7() bool {
	if x != nil {
		return x.A7
	}
	return false
}

func (x *TypeRequest) GetA8() string {
	if x != nil {
		return x.A8
	}
	return ""
}

func (x *TypeRequest) GetA9() []byte {
	if x != nil {
		return x.A9
	}
	return nil
}

type TypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeResponse) Reset() {
	*x = TypeResponse{}
	mi := &file_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeResponse) ProtoMessage() {}

func (x *TypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeResponse.ProtoReflect.Descriptor instead.
func (*TypeResponse) Descriptor() ([]byte, []int) {
	return file_type_proto_rawDescGZIP(), []int{1}
}

var File_type_proto protoreflect.FileDescriptor

const file_type_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"type.proto\x12\n" +
	"type_proto\"\x9d\x01\n" +
	"\vTypeRequest\x12\x0e\n" +
	"\x02a1\x18\x01 \x01(\x01R\x02a1\x12\x0e\n" +
	"\x02a2\x18\x02 \x01(\x02R\x02a2\x12\x0e\n" +
	"\x02a3\x18\x03 \x01(\x05R\x02a3\x12\x0e\n" +
	"\x02a4\x18\x04 \x01(\x03R\x02a4\x12\x0e\n" +
	"\x02a5\x18\x05 \x01(\rR\x02a5\x12\x0e\n" +
	"\x02a6\x18\x06 \x01(\x04R\x02a6\x12\x0e\n" +
	"\x02a7\x18\a \x01(\bR\x02a7\x12\x0e\n" +
	"\x02a8\x18\b \x01(\tR\x02a8\x12\x0e\n" +
	"\x02a9\x18\t \x01(\fR\x02a9\"\x0e\n" +
	"\fTypeResponse2M\n" +
	"\vTypeService\x12>\n" +
	"\aGetType\x12\x17.type_proto.TypeRequest\x1a\x18.type_proto.TypeResponse\"\x00B\x0fZ\r./;type_protob\x06proto3"

var (
	file_type_proto_rawDescOnce sync.Once
	file_type_proto_rawDescData []byte
)

func file_type_proto_rawDescGZIP() []byte {
	file_type_proto_rawDescOnce.Do(func() {
		file_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_type_proto_rawDesc), len(file_type_proto_rawDesc)))
	})
	return file_type_proto_rawDescData
}

var file_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_type_proto_goTypes = []any{
	(*TypeRequest)(nil),  // 0: type_proto.TypeRequest
	(*TypeResponse)(nil), // 1: type_proto.TypeResponse
}
var file_type_proto_depIdxs = []int32{
	0, // 0: type_proto.TypeService.GetType:input_type -> type_proto.TypeRequest
	1, // 1: type_proto.TypeService.GetType:output_type -> type_proto.TypeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_type_proto_init() }
func file_type_proto_init() {
	if File_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_type_proto_rawDesc), len(file_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_type_proto_goTypes,
		DependencyIndexes: file_type_proto_depIdxs,
		MessageInfos:      file_type_proto_msgTypes,
	}.Build()
	File_type_proto = out.File
	file_type_proto_goTypes = nil
	file_type_proto_depIdxs = nil
}
